FROM golang:latest
RUN go get github.com/sdminonne/workflow-controller
RUN CGO_ENABLED=0 GOOS=linux go build -i -installsuffix cgo --ldflags '-extldflags "-static"' -o workflow-controller src/github.com/sdminonne/workflow-controller/main.go
