kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: workflow-controller
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs: ["*"]
- apiGroups:
    - workflow.example.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["*"]
- apiGroups:
  - example.com
  resources:
  - workflows
  verbs: ["*"]
