kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: workflow-controller
subjects:
  - kind: ServiceAccount
    name: workflow-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: workflow-controller
  apiGroup: rbac.authorization.k8s.io
