apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workflow-controller-deployment
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccount: workflow-controller
      containers:
      - name: workflow-controller
        image: vogt1005.scripps.edu:5000/workflow-controller
        args: ["./workflow-controller", "--resource-versions=v1", "--domain=example.com", "--name=workflow"]
